version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payment_db
    environment:
      POSTGRES_DB: payment_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d payment_api"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build: .
    container_name: payment_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=payment_api
      - DB_USER=admin
      - DB_PASSWORD=password123
      - WEBHOOK_SECRET=webhook-secret-key # Or any secret string you want to use for testing
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: npm start

volumes:
  postgres_data: